version: '3'
services:
  product-service-api:
    build: ./Docker-app-2
    volumes:
       - ./user/src/app
    ports:
      - 4000:4000
  product-service:
    build: ./Docker-app
    volumes:
      - ./user/src/app
    ports:
      - 3000:3000
    depends_on:
      - product-service-api